### ISSUE TITLE
Truncate options in subset 1,2,3 picklists to 10 characters

### ISSUE THREAD

**Issue by emmorris** [RhoInc/rave-xplorer#27]
DMEDS would like to display subset labels within the subset 1,2, and 3 picklists at the top of the heat map.  They will provide the text labels within the dataset by putting the text label in the appropriate subset column.  A couple examples are Cohort 1 or Freeze 1.  Since we will be accepting text instead of just having the options as "All" or "1" we need to truncate the labels once they exceed 10 characters so that they don't take up too much horizontal space.

**Comment by samussiah** [comment]
This is a data issue and data should be handled upstream of the renderer.  The [data guidelines](https://github.com/RhoInc/rave-xplorer/wiki/Data-Guidelines).
